"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
var config_1 = require("prisma/config");
var env_1 = require("./src/config/env");
exports.default = (0, config_1.defineConfig)({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
        seed: "prisma/seed.ts"
    },
    datasource: {
        url: env_1.default.databaseUrl,
    },
});
