"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var authMiddleware_1 = require("../middleware/authMiddleware");
var requireProfileComplete_1 = require("../middleware/requireProfileComplete");
var validate_1 = require("../middleware/validate");
var request_schema_1 = require("../schemas/request.schema");
var requestController_1 = require("../controllers/requestController");
var router = express_1.default.Router();
router.use(authMiddleware_1.default);
router.post("/send", requireProfileComplete_1.requireProfileComplete, (0, validate_1.validateBody)(request_schema_1.SendMatchRequestSchema), requestController_1.sendRequest);
router.get("/sent", requestController_1.getSent);
router.get("/received", requestController_1.getReceived);
router.post("/:id/accept", requestController_1.accept);
router.post("/:id/decline", requestController_1.decline);
router.post("/:id/cancel", requestController_1.cancel);
exports.default = router;
